### ISSUE TITLE
Docker Container Fails to Start

### ISSUE THREAD

**Issue by tpaulus** [iloveitaly/lunchmoney-assets#1]
Hi there,

I build and launched a Docker Container from the Dockerfile provided, but it seems that a file, specifically `cron.sh` is missing from the Repo. 

Logs from Docker:
```
bash: cron.sh: No such file or directory
```

Cheers,
Tom

**Comment by iloveitaly** [comment]
@tpaulus I don't use the docker container, so it probably needs some more work. You can copy the cron script from this repo:

https://github.com/iloveitaly/crypto-index-fund-bot/blob/main/scripts/cron.sh

Please submit a PR if you get it working!

**Comment by iloveitaly** [comment]
This should be fixed!
