### ISSUE TITLE
Docker image fails when not on pi

### ISSUE THREAD

**Issue by jaron-l** [iloveitaly/lunchmoney-assets#69]
When running the docker image on a non-pi platform, you get the following error:
```
Updating price data Wed Dec 04 2024 14:29:55 GMT+0000 (Coordinated Universal Time)
(node:8) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:314
                reject(new Error([
                       ^

Error: Failed to launch the browser process! undefined
[19:19:1204/142955.592644:ERROR:zygote_host_impl_linux.cc(101)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:314:24)
    at ChildProcess.emit (node:events:525:35)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v23.3.0
```

When looking through the code, it looks like [`--no-sandbox` is only enabled on pi platforms](https://github.com/iloveitaly/lunchmoney-assets/blob/main/index.ts#L33). When I removed the if check, the code worked for me running the docker on a Linux machine.

I see a couple of options for how to resolve this issue:
1. Enable `--no-sandbox` always
    - This would normally be a security issue because the sandbox protects the client code from making host modications but maybe that's not as big of a concerns since the websites are hard-coded and relatively safe? Alternatively, we could just enable no-sandbox when in docker. I'm not sure why the pi check is there as it shouldn't be needed on a pi unless the pi is also running this in docker.
3. Change the Docker security configuration and add another user
  - More complicated but summarized here: https://stackoverflow.com/questions/76833201/how-to-run-chrome-securely-in-docker

**Comment by iloveitaly** [comment]
PRs welcome to fix!
